### ISSUE TITLE
[Fix] TODO API 응답 프로토콜 통일

### ISSUE THREAD

**Issue by idean3885** [KDS-OurMemory/Server#174]
## 이슈 내용
- TODO API 응답 프로토콜을 통일한다.

|기능명|AS-IS|TO-BE|
|---|---|---|
|TODO 추가|추가 응답 프로토콜 사용|TODO 응답 프로토콜로 통일|
|TODO 단일 조회|단일 조회 응답 프로토콜 사용|TODO 응답 프로토콜로 통일|
|TODO 목록 조회|목록 조회 응답 프로토콜 사용|TODO 응답 프로토콜로 통일|
|TODO 수정|수정 응답 프로토콜 사용|TODO 응답 프로토콜로 통일|
|TODO 삭제|삭제 응답 프로토콜 사용|TODO 응답 프로토콜로 통일|

## 상세 내용
- 클라이언트와 서버 간 유지보수 효율성을 위해 응답 프로토콜을 통일함.

### 응답 프로토콜 수정
- [x] TODO 추가
- [x] TODO 단일 조회
- [x] TODO 목록 조회
- [x] TODO 수정
- [x] TODO 삭제

### 테스트 코드
- [x] TODO 추가
- [x] TODO 단일 조회
- [x] TODO 목록 조회
- [x] TODO 수정
- [x] TODO 삭제

### 문서
- [x] 노션에 수정사항 기록
- [x] TODO API 응답 프로토콜 삭제

## 참고
- 스웨거를 통해 API 문서를 관리하기 위해 노션에 응답 프로토콜 양식을 삭제함.
- 어떤 화면에서 API가 호출되는지 관리하는 용도로 노션 프로토콜 탭을 사용할 예정임.

**Comment by idean3885** [comment]
클라이언트 측에서 기능을 아직 구현하지 않아 요청 프로토콜도 통일함.
서버 측의 영향도만 고려하면 됬기 때문에 통일시킴.
